name: Deploy to Railway

on:
  push:
    branches:
      - produccion

jobs:
  deploy:
    if: github.repository == 'deivisaherreraj/link-bio'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: "link-in-bio"
